// src/routes/apps/kilordle.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import * as wasm from "@lib/ts/wasm";
  import Toast, { postToast } from "@lib/svelte/errors.svelte";
  import { defer } from "@lib/ts/util";

  interface PuzzleData {
    solution: string;
    filled: string;
    submits: string;
  }

  const KEYROWS = [
    "qwertyuiop".split(""),
    "asdfghjkl".split(""),
    ["Go", ..."zxcvbnm".split(""), "Del"],
  ];

  let wasmRef: wasm.Ref | undefined = undefined;

  let word: string = "";
  let puzzles: PuzzleData[] = [];
  let submissionCount: number = 0;
  let wordsLeft: number = 0;
  let foundLetters: Record<string, true> = {};

  let submitError: boolean = false;
  let timeout: any = undefined;

  let keyboard: any = undefined;

  const reset = () => {
    if (!wasmRef) return;

    wasmRef.abi.reset();

    word = "";
    submissionCount = 0;
    submitError = false;
    puzzles = [];
    foundLetters = {};
  };

  const addChar = (c: string) => {
    if (word.length > 4) {
      return;
    }

    word = word + c.toLowerCase();
    submitError = false;
  };

  const pressKey = (key: string): boolean => {
    switch (key) {
      case "Shift":
      case "Control":
      case " ":
        return false;

      case "Enter":
      case "Go": {
        if (word.length < 5) break;
        if (!wasmRef) break;

        const chars = word.split("");
        const codes = chars.map((c) => c.charCodeAt(0));

        defer(() => {
          if (!wasmRef.abi.submitWord(...codes)) {
            submitError = true;
            return;
          }

          const notFound = chars.filter((l) => !foundLetters[l]);
          notFound.forEach((letter) => {
            foundLetters[letter] = true;
          });
        });
        break;
      }

      case "Backspace":
      case "Delete":
      case "Del":
        word = word.slice(0, -1);
        break;

      default:
        if (!key.match(/^[a-zA-Z]$/)) {
          return false;
        }

        addChar(key);
        break;
    }

    return true;
  };

  $: {
    if (submitError) {
      timeout = setTimeout(() => (submitError = false), 1000);
    } else {
      clearTimeout(timeout);
      timeout = undefined;
    }
  }

  onMount(() => {
    const wordles = wasm.fetchAsset("/apps/wordles.txt");
    const words = wasm.fetchAsset("/apps/wordle-words.txt");
    const wasmPromise = wasm.fetchWasm("/apps/kilordle.wasm", {
      postMessage: postToast,
      imports: { setPuzzles: (p: PuzzleData[]) => (puzzles = p) },
      raw: () => ({
        resetSubmission: () => {
          word = "";
          submitError = false;
        },
        incrementSubmissionCount: () => (submissionCount += 1),
        setWordsLeft: (words: number) => (wordsLeft = words),
        addChar: (code: number) => {
          const character = String.fromCharCode(code);
          addChar(character);
        },
      }),
    });

    Promise.all([wasmPromise, wordles, words]).then(([ref, wordles, words]) => {
      const wordlesId = ref.addObj(wordles);
      const wordsId = ref.addObj(words);

      ref.abi.init(wordlesId, wordsId);
      wasmRef = ref;
    });

    keyboard?.focus();

    const listener = (evt: KeyboardEvent) => {
      if (evt.ctrlKey || evt.metaKey || evt.altKey) {
        return;
      }

      if (pressKey(evt.key)) {
        evt.preventDefault();
      }
    };

    window.addEventListener("keydown", listener);

    return () => {
      console.log("unmounting");
      window.removeEventListener("keydown", listener);
    };
  });
</script>

<svelte:head>
  <link rel="manifest" href="/apps/kilordle.webmanifest" />
  <meta name="theme-color" content="#1976D2" />
</svelte:head>

<Toast />

<div class="wrapper">
  <div class="topBar">
    <div class="submitWindow" class:shake={submitError}>
      <div class="letterBox">{word[0] ?? ""}</div>
      <div class="letterBox">{word[1] ?? ""}</div>
      <div class="letterBox">{word[2] ?? ""}</div>
      <div class="letterBox">{word[3] ?? ""}</div>
      <div class="letterBox">{word[4] ?? ""}</div>
    </div>

    <div class="statsBox">
      <div>Guesses: {submissionCount}</div>
      <div>Words: {wordsLeft}</div>
    </div>
  </div>

  <div class="centerArea">
    <!-- <PuzzleArea /> -->
    {#if submissionCount === 0}
      <div class="centerMessage">
        {"No submissions yet. Try typing a word and hitting 'Enter'!"}
      </div>
    {:else if wordsLeft === 0}
      <div class="centerMessage">
        <p>{"You won!"}</p>
        <button class="muiButton" on:click={reset}>Play again</button>
      </div>
    {:else}
      <div class="guessesArea">
        {#each puzzles as puzzle (puzzle.solution)}
          <div class="puzzle">
            <div class="filledBox">
              {#each puzzle.filled.split("") as letter, idx}
                <!--
                  We use the isLower test here instead of checking against
                  space so that in debug builds we can see the actual solution
                  and double-check that everything is kosher. This logic ensures
                  that lowercase letters and space are output as white and
                  uppercase are green.
                -->

                <div
                  class="letterBox"
                  class:green={letter.toLowerCase() == letter}
                >
                  {letter}
                </div>
              {/each}
            </div>

            {#each puzzle.submits.split(",") as submit}
              <div class="submitBox">
                {#each submit.split("") as letter}
                  <div
                    class="letterBox"
                    class:yellow={letter.toUpperCase() === letter}
                  >
                    {letter}
                  </div>
                {/each}
              </div>
            {/each}
          </div>
        {/each}
      </div>
    {/if}
  </div>

  <div bind:this={keyboard} class="keyboard">
    {#each KEYROWS as row, idx}
      <div class="keyboardRow" class:middleRow={idx === 1}>
        {#each row as key}
          <button
            class="keyBox"
            class:gray={foundLetters[key]}
            on:click={() => pressKey(key)}
          >
            {key}
          </button>
        {/each}
      </div>
    {/each}
  </div>
</div>

<style lang="postcss">
  @import "@lib/util.module.css";

  .wrapper {
    height: 100vh;
    width: 100vw;

    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;

    touch-action: manipulation;
  }

  .topBar {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    border-bottom: 4px solid gray;

    @media (--max-sm) {
      padding: 4px 8px 4px 4px;
    }

    @media (--min-sm) {
      position: relative;
      padding: 4px 16px 4px 16px;
    }
  }

  .submitWindow {
    font-size: 2rem;
    font-family: "Dank Mono", "Fira Code", monospace;

    display: flex;
    flex-direction: row;
    align-items: center;
    gap: 4px;

    @media (--max-sm) {
    }

    @media (--min-sm) {
      position: absolute;
      left: 50%;
      transform: translate(-50%, 0%);
    }
  }

  .statsBox {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    justify-content: center;

    margin-left: auto;
  }

  .letterBox {
    border-radius: 8px;
    border: 1px solid gray;
    width: 1em;
    height: 1.5em;

    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;

    text-transform: uppercase;
  }

  .centerArea {
    overflow-y: scroll;
    flex: 1;
    max-height: inherit;

    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    justify-content: center;
  }

  .guessesArea {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;

    @media (--min-lg) {
      max-width: lg;
    }

    padding: 8px;
    gap: 1rem;
  }

  .centerMessage {
    flex: 1;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
  }

  .puzzle {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .filledBox {
    display: flex;
    flex-direction: row;
    gap: 4px;
  }

  .submitBox {
    display: flex;
    flex-direction: row;
    gap: 4px;
  }

  .keyboard {
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    align-items: center;
    gap: 8px;

    font-weight: bold;
    padding: 1em 4px 1em 4px;

    font-size: 24px;
  }

  .keyboardRow {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    gap: 4px;
    justify-content: space-between;

    width: 100%;
    max-width: 500px;
  }

  .middleRow {
    @media (--max-sm) {
      padding: 0px 8px 0px 8px;
    }

    @media (--min-sm) {
      padding: 0px 16px 0px 16px;
    }
  }

  .keyBox {
    border-radius: 8px;
    border: 1px solid gray;

    height: 58px;
    padding: 4px;
    text-decoration: none;
    color: black;

    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    flex-grow: 1;
    flex-basis: 0;
    text-transform: uppercase;
  }

  .yellow {
    background-color: yellow;
  }

  .green {
    background-color: lightgreen;
  }

  .gray {
    background-color: gray;
  }

  /* https://css-tricks.com/snippets/css/shake-css-keyframe-animation/ */
  .shake {
    backface-visibility: hidden;
    perspective: 1000px;

    @media (--max-sm) {
      animation: shake 0.82s cubic-bezier(0.36, 0.07, 0.19, 0.97) both;
    }

    @media (--min-sm) {
      animation: shake-translated 0.82s cubic-bezier(0.36, 0.07, 0.19, 0.97)
        both;
    }
  }

  @keyframes shake-translated {
    0%,
    100% {
      transform: translate(-50%, 0%);
    }

    10%,
    90% {
      transform: translate(-50%, 0%) translate3d(-1px, 0, 0);
    }

    20%,
    80% {
      transform: translate(-50%, 0%) translate3d(2px, 0, 0);
    }

    30%,
    50%,
    70% {
      transform: translate(-50%, 0%) translate3d(-4px, 0, 0);
    }

    40%,
    60% {
      transform: translate(-50%, 0%) translate3d(4px, 0, 0);
    }
  }

  @keyframes shake {
    10%,
    90% {
      transform: translate3d(-1px, 0, 0);
    }

    20%,
    80% {
      transform: translate3d(2px, 0, 0);
    }

    30%,
    50%,
    70% {
      transform: translate3d(-4px, 0, 0);
    }

    40%,
    60% {
      transform: translate3d(4px, 0, 0);
    }
  }
</style>

// pages/toys/kilordle.tsx
import React from "react";
import type { Dispatch, SetStateAction } from "react";
import css from "./kilordle.module.css";
import * as wasm from "components/wasm";
import type { WasmRef } from "components/wasm";
import cx from "classnames";
import create from "zustand";
import { useToast, ToastColors } from "components/errors";

interface PuzzleData {
  solution: string;
  filled: string;
  submits: string[];
}

interface PuzzleWasmData {
  solution: string;
  filled: string;
  submits: string;
}

interface KilordleCb {
  submit: () => void;
  addChar: (c: string) => void;
  deleteChar: () => void;
  setPuzzles: (puzzles: PuzzleWasmData[]) => void;
  setWordsLeft: (wordsLeft: number) => void;
  setWasmRef: (wasmRef: WasmRef) => void;
  clearError: () => void;
}

interface KilordleState {
  wasmRef: WasmRef | undefined;
  foundLetters: Record<string, true>;
  submissionCount: number;
  wordsLeft: number;
  submitError: boolean;
  word: string;
  puzzles: PuzzleData[];
  callbacks: KilordleCb;
}

// https://github.com/vercel/next.js/tree/canary/examples/with-web-worker

const KEYROWS = [
  "qwertyuiop".split(""),
  "asdfghjkl".split(""),
  ["Go", ..."zxcvbnm".split(""), "Del"],
];

const pressKey = (key: string, cb: KilordleCb): boolean => {
  switch (key) {
    case "Shift":
    case "Control":
    case " ":
      return false;

    case "Enter":
    case "Go":
      cb.submit();
      break;

    case "Backspace":
    case "Delete":
    case "Del":
      cb.deleteChar();
      break;

    default:
      if (!key.match(/^[a-zA-Z]$/)) {
        return false;
      }

      cb.addChar(key);
      break;
  }

  return true;
};

const useStore = create<KilordleState>((set, get) => {
  const deleteChar = () => set((state) => ({ word: state.word.slice(0, -1) }));
  const addChar = (c: string) => {
    const word = get().word;
    if (word.length > 4) {
      return;
    }

    set({ word: word + c.toLowerCase(), submitError: false });
  };

  const submit = () => {
    const state = get();
    const { word, foundLetters, submissionCount, wasmRef } = get();

    if (word.length < 5) {
      return;
    }

    if (!wasmRef) {
      return;
    }

    const chars = word.split("");
    const codes = chars.map((c) => c.charCodeAt(0));

    wasmRef.defer.submitWord(...codes).then((success: boolean) => {
      if (!success) {
        set({ submitError: true });
        return;
      }

      const newFounds: Record<string, true> = {};
      let foundCount = 0;

      chars.forEach((letter) => {
        if (!foundLetters[letter]) {
          newFounds[letter] = true;
          foundCount += 1;
        }
      });

      if (foundCount > 0) {
        set({
          foundLetters: { ...foundLetters, ...newFounds },
        });
      }

      set({
        word: "",
        submissionCount: submissionCount + 1,
        submitError: false,
      });
    });
  };

  const setPuzzles = (puzzles: PuzzleWasmData[]) => {
    set({
      puzzles: puzzles.map((puzzle) => {
        return {
          ...puzzle,
          submits: puzzle.submits.split(","),
        };
      }),
    });
  };

  const setWordsLeft = (wordsLeft: number) => {
    set({ wordsLeft });
  };

  const clearError = () => set({ submitError: false });

  const setWasmRef = (wasmRef: WasmRef) => set({ wasmRef });

  return {
    word: "",
    wasmRef: undefined,
    submissionCount: 0,
    submitError: false,
    wordsLeft: 0,
    foundLetters: {},
    puzzles: [],
    callbacks: {
      submit,
      addChar,
      deleteChar,
      setPuzzles,
      setWordsLeft,
      clearError,
      setWasmRef,
    },
  };
});

const TopBar: React.VFC = () => {
  const word = useStore((state) => state.word.toUpperCase());
  const submitError = useStore((state) => state.submitError);
  const submissionCount = useStore((state) => state.submissionCount);
  const wordsLeft = useStore((state) => state.wordsLeft);
  const cb = useStore((state) => state.callbacks);

  const timeoutRef = React.useRef<any>();

  React.useEffect(() => {
    clearTimeout(timeoutRef.current);
    timeoutRef.current = undefined;

    if (submitError) {
      timeoutRef.current = setTimeout(() => cb.clearError(), 1000);
    }
  }, [cb, submitError]);

  return (
    <div className={css.topBar}>
      <div></div>

      <div className={cx(css.submitWindow, submitError && css.shake)}>
        <div className={css.letterBox}>{word[0]}</div>
        <div className={css.letterBox}>{word[1]}</div>
        <div className={css.letterBox}>{word[2]}</div>
        <div className={css.letterBox}>{word[3]}</div>
        <div className={css.letterBox}>{word[4]}</div>
      </div>

      <div className={css.statsBox}>
        <div>Guesses: {submissionCount}</div>
        <div>Words: {wordsLeft}</div>
      </div>
    </div>
  );
};

const Keyboard: React.VFC = () => {
  const keyboardRef = React.useRef<HTMLInputElement>(null);
  const foundLetters = useStore((state) => state.foundLetters);
  const cb = useStore((state) => state.callbacks);

  React.useEffect(() => {
    keyboardRef.current?.focus();
  }, [keyboardRef]);

  React.useEffect(() => {
    const listener = (evt: KeyboardEvent) => {
      if (evt.ctrlKey || evt.metaKey || evt.altKey) {
        return;
      }

      if (pressKey(evt.key, cb)) {
        evt.preventDefault();
      }
    };

    window.addEventListener("keydown", listener);

    return () => {
      console.log("deleting");
      window.removeEventListener("keydown", listener);
    };
  }, [cb]);

  return (
    <div ref={keyboardRef} className={css.keyboard}>
      {KEYROWS.map((row, idx) => {
        return (
          <div key={idx} className={css.keyboardRow}>
            {row.map((key) => {
              return (
                <button
                  key={key}
                  className={cx(css.keyBox, foundLetters[key] && css.gray)}
                  onClick={() => pressKey(key, cb)}
                >
                  {key}
                </button>
              );
            })}
          </div>
        );
      })}
    </div>
  );
};

const Puzzle: React.VFC<{ puzzle: PuzzleData }> = ({ puzzle }) => {
  return (
    <div className={css.puzzle}>
      <div className={css.filledBox}>
        {puzzle.filled.split("").map((letter, idx) => {
          const lower = letter.toLowerCase();
          const isLower = letter === lower;

          // We use the isLower test here instead of checking against space
          // so that in debug builds we can see the actual solution and
          // double-check that everything is kosher. This logic ensures that
          // lowercase letters and space are output as white and uppercase
          // are green.
          return (
            <div key={idx} className={cx(css.letterBox, isLower || css.green)}>
              {letter.toUpperCase()}
            </div>
          );
        })}
      </div>

      {puzzle.submits.map((submit) => (
        <div key={submit} className={css.submitBox}>
          {submit.split("").map((letter, idx) => {
            const upper = letter.toUpperCase();
            const isUpper = letter === upper;

            return (
              <div
                key={idx}
                className={cx(css.letterBox, isUpper && css.yellow)}
              >
                {upper}
              </div>
            );
          })}
        </div>
      ))}
    </div>
  );
};

const PuzzleArea: React.VFC = () => {
  const puzzles = useStore((state) => state.puzzles);
  const wordsLeft = useStore((state) => state.wordsLeft);
  const submissionCount = useStore((state) => state.submissionCount);

  if (submissionCount === 0) {
    return (
      <div className={css.centerMessage}>
        {"No submissions yet. Try typing a word and hitting 'Enter'!"}
      </div>
    );
  }

  if (wordsLeft === 0) {
    return (
      <div className={css.centerMessage}>
        {"You won! Refresh to play again."}
      </div>
    );
  }

  return (
    <div className={css.guessesArea}>
      {puzzles.map((puzzle) => (
        <Puzzle key={puzzle.solution} puzzle={puzzle} />
      ))}
    </div>
  );
};

export const Kilordle: React.VFC = () => {
  const cb = useStore((state) => state.callbacks);
  const toast = useToast();

  React.useEffect(() => {
    const postMessage = (tag: string, data: any) => {
      console.log(tag, data);

      if (typeof data === "string") {
        toast.add(ToastColors[tag] ?? "green", null, data);
      }
    };

    const wasmPromise = wasm.fetchWasm("/assets/kilordle.wasm", {
      postMessage,
      imports: { setPuzzles: cb.setPuzzles },
      raw: { setWordsLeft: cb.setWordsLeft },
    });

    wasmPromise.then((ref) => {
      ref.abi.init();
      cb.setWasmRef(ref);
    });
  }, [toast, cb]);

  return (
    <div className={css.wrapper}>
      <TopBar />
      <div className={css.centerArea}>
        <PuzzleArea />
      </div>
      <Keyboard />
    </div>
  );
};

export default Kilordle;
