// src/svelte/errors.svelte
<script lang="ts" context="module">
  import { writable } from "svelte/store";

  interface ToastData {
    color: string;
    text: string;
  }

  // Use Map here, which iterates in insertion order
  const store = writable({ toasts: [], toastId: 0 });

  type ToastColor =
    | "red"
    | "green"
    | "orange"
    | "blue"
    | "error"
    | "warn"
    | "info"
    | "log"
    | "success";

  export const ToastColors: Record<string, ToastColor> = {
    red: "red",
    green: "green",
    blue: "blue",
    orange: "orange",
    error: "red",
    info: "info",
    log: "log",
    success: "success",
    warn: "warn",
  };

  const ColorMap: Record<ToastColor, string> = {
    red: "red",
    green: "green",
    blue: "blue",
    orange: "orange",
    error: "red",
    info: "blue",
    log: "blue",
    success: "green",
    warn: "orange",
  };

  export function addToast(
    kind: ToastColor,
    time: number | null,
    ...toasts: string[]
  ) {
    const color = ColorMap[kind];
    const newToasts = toasts.map((text) => ({ color, text }));
    store.update((state) => {
      const toasts = [...state.toasts, ...newToasts];

      return { toasts, toastId: state.toastId };
    });

    const count = toasts.length;
    setTimeout(() => {
      store.update((state) => ({
        toasts: state.toasts.slice(count),
        toastId: state.toastId + count,
      }));
    }, time ?? 3 * 1000);
  }

  export const postToast = (tag: string, data: any): void => {
    console.log(tag, data);

    if (typeof data === "string") {
      addToast(ToastColors[tag] ?? "green", null, data);
    }
  };
</script>

<script lang="ts">
  $: ({ toasts, toastId } = $store);
</script>

<div class="toastCorner">
  <div class="toastContent">
    {#each toasts as { color, text }, idx (idx + toastId)}
      <div class="toast" style={`background-color: ${color}`}>
        {text}
      </div>
    {/each}
  </div>
</div>

<style lang="postcss">
  .toastCorner {
    position: fixed;
    left: 8px;
    bottom: 8px;
    z-index: 10000;
    width: 300px;

    overflow: hidden;
    display: flex;
    flex-direction: column-reverse;
    max-height: calc(100vh - 8px);
  }

  .toastContent {
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;

    gap: 8px;
    padding-left: 4px;
  }

  .toast {
    min-height: 1.5rem;
    width: 100%;

    color: white;
    font-weight: bold;

    padding: 8px 4px 8px 16px;
  }
</style>

// src/errors.tsx
import React from "react";
import css from "./errors.module.css";
import cx from "classnames";
import create from "zustand";

type AddToast = (kind: ToastColor, time: number | null, ...t: string[]) => void;

type ToastColor =
  | "red"
  | "green"
  | "orange"
  | "blue"
  | "error"
  | "warn"
  | "info"
  | "log"
  | "success";

export const ToastColors: Record<string, ToastColor> = {
  red: "red",
  green: "green",
  blue: "blue",
  orange: "orange",
  error: "red",
  info: "info",
  log: "log",
  success: "success",
  warn: "warn",
};

const ColorMap: Record<ToastColor, string> = {
  red: css.red,
  green: css.green,
  blue: css.blue,
  orange: css.orange,
  error: css.red,
  info: css.blue,
  log: css.blue,
  success: css.green,
  warn: css.orange,
};

interface ToastData {
  color: string;
  text: string;
}

interface ToastCallbacks {
  add: AddToast;
}

// Use Map here, which iterates in insertion order
interface ToastState {
  toasts: ToastData[];
  toastId: number;
  cb: ToastCallbacks;
}

const useStore = create<ToastState>((set) => {
  function popToast(count: number) {
    // TODO bounds check?
    set((state) => ({
      toasts: state.toasts.slice(count),
      toastId: state.toastId + count,
    }));
  }

  function add(kind: ToastColor, time: number | null, ...toasts: string[]) {
    const color = ColorMap[kind];
    set((state) => ({
      toasts: [...state.toasts, ...toasts.map((text) => ({ color, text }))],
    }));

    setTimeout(() => popToast(toasts.length), time ?? 3 * 1000);
  }

  return {
    toasts: [],
    toastId: 0,
    cb: { add },
  };
});

const getToasts = (state: ToastState) => state.toasts;
const getToastId = (state: ToastState) => state.toastId;
const getCallbacks = (state: ToastState): ToastCallbacks => state.cb;

export const useToastStore = useStore;

export function useToast(): ToastCallbacks {
  const cb = useStore(getCallbacks);

  return cb;
}

export const ToastCorner: React.VFC = () => {
  const toasts = useStore(getToasts);
  const toastId = useStore(getToastId);

  return (
    <div className={css.toastCorner}>
      <div className={css.toastContent}>
        {toasts.map(({ color, text }, idx) => {
          return (
            <div key={idx + toastId} className={cx(css.toast, color)}>
              {text}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export const postToast = (tag: string, data: any): void => {
  const toast = useStore.getState().cb;

  console.log(tag, data);

  if (typeof data === "string") {
    toast.add(ToastColors[tag] ?? "green", null, data);
  }
};
